# Categorization (이항변수화)

![데이터변환3_범주화](imgs/데이터변환3_범주화.png)

<hr>

## ■ 이항변수화란 (Binarization)
- 이산형화가 연속형 범주를 다수의 구간으로 범주화 하는 것이라면, 이항변수화는 '1'과 '0'의 2개의 값으로 가변환 하는 것을 말함.
- ex) 어떤 수치를 기준으로 1,0 등으로 나뉘는 경우 (백만원 이상이면 세금부여대상자)
- 연관 단어로 : 베르누이 시행, 이항분포(binomial distribution)

## ■ 베르누이 시행
- **어떤 실험을 반복해서 시행한다고 했을 때 각 시행마다 "성공(success, 1)" 또는 "실패(failure, 0)"의 두 가지 경우의 수만 나오는 경우,** 이런 시행을 "베르누이 시행(Bernoulli trial)"이라고 합니다. 
 
## ■ 이항분포
- 그리고 성공확률이 p인 베르누이 시행을 n번 반복했을 때 성공하는 횟수를 X라 하면, 확률변수 X는 모수 n과 p인 이항분포(Binomial distributio)을 따른다고 함.

## ■수치형 변수의 이항변수화 
- 연속형 변수를 특정 기준값 이하면 '0' 특정 기준값 초과면 '1' 두개의 값 변수로 변환
- sklearn.preprocessing.Binarizer(), binarize()
![이항변수화변환](imgs/이항변수화변환.jfif)



In [2]:
import numpy as np
X = np.array([[10, -10, 1],
              [5, -2, 2],
              [-5, 10, -3]])
X

array([[ 10, -10,   1],
       [  5,  -2,   2],
       [ -5,  10,  -3]])

In [3]:
# 방법1 - Binarizer() -> fit(), transform()
# threshold = 0.0 default

from sklearn.preprocessing import Binarizer

b = Binarizer().fit(X) # Binarizer  
b.transform(X)

array([[1, 0, 1],
       [1, 0, 1],
       [0, 1, 0]])

In [4]:
# threshold = 2.0 default
b2 = Binarizer(threshold=3).fit(X) # Binarizer 객체 
b2.transform(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [5]:
# 방법2 - binarize()
from sklearn.preprocessing import binarize

# copy옵션 = False 면 X 자체를 손댐.
binarize(X, threshold=5, copy=False)
X

array([[1, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

### 출처
- https://rfriend.tistory.com/271